name: append
on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
    append_1_to_pr_body_not_commit:
        runs-on: ubuntu-latest
        steps:
            - name: append feature number to pr body pr branch = feat/(issueNumber)
              uses: actions/github-script@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const pr = await github.pulls.get({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.issue.number
                      });
                      const body = pr.data.body;
                      const issueNumber= pr.data.head.ref.split('/')[1];
                      const newBody = body + "\n\n" + "issueNumber: #" + issueNumber;
                      await github.pulls.update({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            pull_number: context.issue.number,
                            body: newBody
                        });
