name: echo_pr_body
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
    echo_pr_body:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: echo pr body
              run: echo "${{ github.event.pull_request.body }}"
