name: append
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
    append_1_to_pr_body_not_commit:
        runs-on: ubuntu-latest
        steps:
            - name: append feature number to pr body feat/1 -> feat/1, #1
              uses: actions/github-script@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const pr = await github.pulls.get({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.issue.number
                      });
                      const body = pr.data.body; 
                    console.log(body);
